##git aliases
alias gs='git status'
alias gA='git add'
alias ga='git add -A'
alias gc='git commit -m'
alias gr='git remote -v'
alias gpush='git push origin master'
alias gpull='git pull origin master'
alias gbd='git branch -b'
alias gbD='git branch -D'
alias gbush='git push origin :'
alias grr='git remote remove '
alias greset='git set-url origin'
alias gdiff='git diff'
alias greset_head='git reset HEAD'
alias gchk_head='git checkout HEAD'
alias glog='git log'
alias gpretty='git log --pretty=oneline'
alias gsquash='git rebase -i HEAD~'
alias grecommit='git commit --amend'