##git aliases
alias gs='git status'
alias ga='git add -A'
alias gc='git commit -m'
alias gr='git remote -v'
alias gpush='git push origin'
alias gpull='git pull origin'
alias gb='git checkout -b'
alias gbD='git branch -D'
alias gd='git diff'
alias gchk_head='git checkout HEAD'
alias glog='git log'
alias gpretty='git log --pretty=oneline'
alias grecommit='git commit --amend'
alias gclone='git clone'
alias gf='git fetch'
alias gm='git merge'
alias gt='git stash'
alias gtp='git stash pop'
alias gi='git init'