# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# My Fedora @Redhat Aliases
if [ -f ~/fedora23aliases.sh ]; then
		. ~/fedora23aliases.sh
fi

# My Git Aliases
if [ -f ~/git_aliases.sh ]; then
	. ~/git_aliases.sh	
fi		
