# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
GIT_PROMPT_ONLY_IN_REPO=1
source ~/.bash-git-prompt/gitprompt.sh

if [ -f ~/fedoraaliases.sh ]; then
	. ~/fedoraaliases.sh
fi

if [ -f ~/git_aliases.sh ]; then
	. ~/git_aliases.sh
fi

export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH

export SPARK_HOME=/usr/local/spark
export PATH=$SPARK_HOME/bin:$PATH

export PYSPARK_DRIVER_PYTHON=jupyter
export PYSPARK_DRIVER_PYTHON_OPTS='notebook'
