alias subl="/home/sarah/softwares/sublime_text_3/sublime_text" #path for sublime text
alias pycharm="/home/sarah/softwares/pycharm-community-5.0.4/bin/pycharm.sh" # path for pycharm
alias jsonview="python -m json.tool" #pretty json viewer, command jsonview <filename>
alias jsoncolor="pygmentize -l javascript" # colored pretty json, command jsonview | jsoncolor
alias getit="sudo dnf install" #shorcut for installing through rpm
alias findit="sudo dnf search" # shortcut to check through the rpm
alias hist="history"
alias histgp='history | grep'
alias ll="ls-alt"
alias pingo='ping 8.8.8.8'
alias vdb='mongo --host 10.70.49.147:27017'
alias eclipse='/home/sarah/Downloads/eclipse/eclipse'
