##git aliases
alias gs='git status'
alias gA='git add'
alias ga='git add -A'
alias gc='git commit -m'
alias gr='git remote -v'
alias gpush='git push origin master'
alias gpull='git pull origin master'
alias gbd='git branch -b'
alias gbD='git branch -D'
alias gbush='git push origin :'
alias grr='git remote remove '
alias greset='git set-url origin'
alias gdiff='git diff'
alias gclone='git clone'
alias grr='git remote remove '
alias greset_origin='git set-url origin'
alias gchk_head='git checkout HEAD' # from git add to abck
alias greset_head='git reset HEAD' # from staging to back